# Generated by Django 3.2.8 on 2021-11-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newbiz', '0004_remove_customer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
